name: Keep Render App Awake (ping)

on:
  schedule:
    - cron: "*/5 * * * *"  # 5분마다 실행
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send ping to Render app
        run: curl -v https://hightensions.site/
